# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/saga/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/saga/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/htc/saga/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
	vendor/htc/saga/proprietary/lib/libqc-opt.so:obj/lib/libqc-opt.so

# All the blobs necessary for saga
PRODUCT_COPY_FILES += \
    vendor/htc/saga/proprietary/bin/akmd:/system/bin/akmd \
    vendor/htc/saga/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/saga/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/saga/proprietary/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/saga/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/saga/proprietary/bin/snd3254:system/bin/snd3254 \
    vendor/htc/saga/proprietary/etc/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/saga/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/htc/saga/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/htc/saga/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/htc/saga/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/htc/saga/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/htc/saga/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/saga/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/saga/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/saga/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/saga/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/htc/saga/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/htc/saga/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/htc/saga/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/htc/saga/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/htc/saga/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/saga/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/htc/saga/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/saga/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/saga/proprietary/lib/hw/camera.vendor.msm7x30.so:/system/lib/hw/camera.vendor.msm7x30.so \
    vendor/htc/saga/proprietary/lib/hw/gps.msm7x30.so:/system/lib/hw/gps.msm7x30.so \
    vendor/htc/saga/proprietary/lib/libcameraface.so:/system/lib/libcameraface.so \
    vendor/htc/saga/proprietary/lib/libcamerapp.so:/system/lib/libcamerapp.so \
    vendor/htc/saga/proprietary/lib/libchromatix_s5k4e1gx_default_video.so:/system/lib/libchromatix_s5k4e1gx_default_video.so \
    vendor/htc/saga/proprietary/lib/libchromatix_s5k4e1gx_preview.so:/system/lib/libchromatix_s5k4e1gx_preview.so \
    vendor/htc/saga/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/saga/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/saga/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/saga/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/saga/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
    vendor/htc/saga/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/saga/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/saga/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/saga/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/htc/saga/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/htc/saga/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/htc/saga/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/saga/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/saga/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/htc/saga/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/saga/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/htc/saga/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/saga/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/saga/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/saga/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/saga/proprietary/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
    vendor/htc/saga/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so
